# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from .User2_0 import User2_0

from .escape_type_service import Escape_typeService
from .uri_service import UriService

from .http_client import HTTPClient


class Client:
    def __init__(self, base_uri="http://localhost:5000"):
        http_client = HTTPClient(base_uri)
        self.escape_type = Escape_typeService(http_client)
        self.uri = UriService(http_client)
        self.close = http_client.close
