# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
using import "EnumAdminClearanceLevel.capnp".EnumAdminClearanceLevel;
@0xafe0adbd57c12353;

struct Admin {
  clearanceLevel @0 :EnumAdminClearanceLevel;
}
