# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from . import handlers


async def users_get(request):
    """
    Get list of all developers
    It is handler for GET /users
    """
    return handlers.users_getHandler(request)


async def users_post(request):
    """
    Add user
    It is handler for POST /users
    """
    return handlers.users_postHandler(request)


async def users_byUsername_get(request, username):
    """
    Get information on a specific user
    It is handler for GET /users/<username>
    """
    return handlers.users_byUsername_getHandler(request, username)
