#%RAML 1.0
title: Notes Example API
baseUri: http://localhost:5000
mediaType: application/json
/resources:
  displayName: Resources
  get:
    description: Get a resource
  post:
    description: Post a resource
protocols: [HTTP, HTTPS]


