# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
using import "EnumEnumCityEnumParks.capnp".EnumEnumCityEnumParks;
@0x851c6a9c2bfa861e;

struct EnumCity {
  enumParks @0 :EnumEnumCityEnumParks;
  name @1 :Text;
}
