# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
@0x9a9eadaa8c275fee;

struct NumberFormat {
  d @0 :Float64;
  f @1 :Float64;
  i @2 :Int16;
  i16 @3 :Int16;
  i32 @4 :Int32;
  i64 @5 :Int64;
  i8 @6 :Int8;
  l @7 :Int32;
  num @8 :Float64;
}
