# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from .File import File

from .tree_service import TreeService

from .http_client import HTTPClient


class Client:
    def __init__(self, base_uri="http://localhost:5000"):
        http_client = HTTPClient(base_uri)
        self.tree = TreeService(http_client)
        self.close = http_client.close
