# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class AnimalsidService:
    def __init__(self, client):
        self.client = client

    def animalsid_get(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        get animal
        It is method for GET /animals/{id}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/animals/" + id
        return self.client.get(uri, None, headers, query_params, content_type)
