# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from flask import Blueprint
try:
    import handlers
except ImportError:
    from . import handlers


coolness_api = Blueprint('coolness_api', __name__)


@coolness_api.route('/coolness', methods=['POST'])
def CreateSomethingCool():
    """
    It is handler for POST /coolness
    """
    return handlers.CreateSomethingCoolHandler()
