-- DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

local functions = {};
functions.helloworld_get_handler = require("handlers.helloworld_get_handler")
functions.users_get_handler = require("handlers.users_get_handler")
functions.users_post_handler = require("handlers.users_post_handler")
functions.usersuser_id_get_handler = require("handlers.usersuser_id_get_handler")
functions.usersuser_id_delete_handler = require("handlers.usersuser_id_delete_handler")
functions.get_user_address_by_id_handler = require("handlers.get_user_address_by_id_handler")
return functions