package main

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"github.com/gorilla/mux"
	"net/http"
)

// ResourcesInterface is interface for /resources root endpoint
type ResourcesInterface interface { // Get is the handler for GET /resources
	// Get a resource
	Get(http.ResponseWriter, *http.Request)
	// Post is the handler for POST /resources
	// Post a resource
	Post(http.ResponseWriter, *http.Request)
}

// ResourcesInterfaceRoutes is routing for /resources root endpoint
func ResourcesInterfaceRoutes(r *mux.Router, i ResourcesInterface) {
	r.HandleFunc("/resources", i.Get).Methods("GET")
	r.HandleFunc("/resources", i.Post).Methods("POST")
}
