-- DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
local users_api = require("users_api")

httpd = require('http.server').new("0.0.0.0", 5000)

users_api(httpd)

httpd:start()