-- DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

local handlers = require("handlers.handlers")

function init(httpd)
    httpd:route({ path = '/users', method = 'GET'}, handlers.users_get_handler)
    httpd:route({ path = '/users', method = 'POST'}, handlers.users_post_handler)
    httpd:route({ path = '/users/:username', method = 'GET'}, handlers.usersusername_get_handler)
end

return init