# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

try:
    import handlers
except ImportError:
    from . import handlers


async def users_post(request):
    """
    create user
    It is handler for POST /users
    """
    return handlers.users_postHandler(request)
