# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from sanic import Blueprint
from sanic.views import HTTPMethodView
from sanic.response import text
from . import users_api


users_if = Blueprint('users_if')


class usersView(HTTPMethodView):

    async def post(self, request):

        return await users_api.users_post(request)


users_if.add_route(usersView.as_view(), '/users')
