# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from sanic import Blueprint
from sanic.views import HTTPMethodView
from sanic.response import text
from . import tree_api


tree_if = Blueprint('tree_if')


class api_v1_root_bypathView(HTTPMethodView):

    async def get(self, request, path=""):

        return await tree_api.get(request, path)


tree_if.add_route(api_v1_root_bypathView.as_view(), '/api/v1/root/', strict_slashes=True)
tree_if.add_route(api_v1_root_bypathView.as_view(), '/api/v1/root/<path:path>')
