# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from flask import Blueprint

try:
    import handlers
except ImportError:
	from . import handlers


users_api = Blueprint('users_api', __name__)


@users_api.route('/users', methods=['POST'])
def users_post():
    """
    create user
    It is handler for POST /users
    """
    return handlers.users_postHandler()
