-- DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
local helloworld_api = require("helloworld_api")
local users_api = require("users_api")

httpd = require('http.server').new("0.0.0.0", 5000)

helloworld_api(httpd)
users_api(httpd)

httpd:start()