-- DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

local handlers = require("handlers.handlers")

function init(httpd)
    httpd:route({ path = '/users', method = 'GET'}, handlers.users_get_handler)
    httpd:route({ path = '/users', method = 'POST'}, handlers.users_post_handler)
    httpd:route({ path = '/users/:userId', method = 'GET'}, handlers.usersuser_id_get_handler)
    httpd:route({ path = '/users/:userId', method = 'DELETE'}, handlers.usersuser_id_delete_handler)
    httpd:route({ path = '/users/:userId/address/:addressId', method = 'GET'}, handlers.get_user_address_by_id_handler)
end

return init