-- DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

local functions = {};
functions.users_get_handler = require("handlers.users_get_handler")
functions.users_post_handler = require("handlers.users_post_handler")
functions.usersusername_get_handler = require("handlers.usersusername_get_handler")
return functions