# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from flask import Blueprint
import handlers


escape_type_api = Blueprint('escape_type_api', __name__)


@escape_type_api.route('/escape_type', methods=['POST'])
def escape_type_post():
    """
    It is handler for POST /escape_type
    """
    return handlers.escape_type_postHandler()
