# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from flask import Blueprint
import handlers


uri_api = Blueprint('uri_api', __name__)


@uri_api.route('/uri/<users_id>', methods=['GET'])
def uri_byUsers_id_get(users_id):
    """
    It is handler for GET /uri/<users-id>
    """
    return handlers.uri_byUsers_id_getHandler(users_id)
