# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from flask import Blueprint
import handlers


files_api = Blueprint('files_api', __name__)


@files_api.route('/files/', defaults={'path': ''}, methods=['GET'], strict_slashes=False)
@files_api.route('/files/<path:path>', methods=['GET'])
def files_byPath_get(path):
    """
    It is handler for GET /files/<path:*>
    """
    return handlers.files_byPath_getHandler(path)
