# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from flask import Blueprint
import handlers


tree_api = Blueprint('tree_api', __name__)


@tree_api.route('/api/v1/root/', defaults={'path': ''}, methods=['GET'], strict_slashes=False)
@tree_api.route('/api/v1/root/<path:path>', methods=['GET'])
def get(path):
    """
    It is handler for GET /api/v1/root/<path:*>
    """
    return handlers.getHandler(path)
