# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from flask import Flask, send_from_directory, send_file
from path_api import path_api

import os
dir_path = os.path.dirname(os.path.realpath(__file__))

app = Flask(__name__)

app.register_blueprint(path_api)


if __name__ == "__main__":
    app.run(debug=True)
