# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from enum import Enum


class EnumString(Enum):
    str_a = "str_a"
    str_b = "str_b"
    _1string = "1string"
    string_one_two = "string.one-two"
