# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
from .File import File
from .unhandled_api_error import UnhandledAPIError
from .unmarshall_error import UnmarshallError


class FilesService:
    def __init__(self, client):
        self.client = client

    async def files_byPath_get(self, path, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /files/{path:*}
        """
        uri = self.client.base_url + "/files" + path
        resp = await self.client.get(uri, None, headers, query_params, content_type)
        try:
            if resp.status == 200:
                return File(await resp.json()), resp
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except Exception as e:
            raise UnmarshallError(resp, e.message)
