# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from app import app

import gevent
from gevent.pywsgi import WSGIServer
from gevent.pool import Pool
from gevent import monkey

import signal

monkey.patch_all()


server = WSGIServer(('', 5000), app, spawn=Pool(None))


def stop():
    server.stop()


gevent.signal(signal.SIGINT, stop)


if __name__ == "__main__":
    server.serve_forever()
