# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
using Go = import "/go.capnp";
@0xa7e23d857e502785;

$Go.package("main");
$Go.import("main");
enum EnumAdminClearanceLevel {
  low @0;
  high @1;
}
