# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from sanic import Blueprint
from sanic.views import HTTPMethodView
from sanic.response import text
from . import path_api


path_if = Blueprint('path_if')


class The__pathView(HTTPMethodView):

    async def get(self, request, path=""):

        return await path_api.byPath_get(request, path)


path_if.add_route(The__pathView.as_view(), '/', strict_slashes=True)
path_if.add_route(The__pathView.as_view(), '/<path:path>')
